"""Serialize a Model to LDR text (LDraw File Format, line types 0 and 1).

Spec reference: https://www.ldraw.org/article/218.html
  - Line type 0: `0 <text>` (comments/META commands). The first line of a
    file becomes its title.
  - Line type 1: `1 <colour> x y z a b c d e f g h i <file>` places a
    sub-file (here, always an official part) with the given color and
    the standard 3x3 rotation/scale matrix.
"""

from __future__ import annotations

from pathlib import Path

from .lattice import placement_to_ldraw
from .model import Model

LDR_LINE_TEMPLATE = "1 {color} {x} {y} {z} {matrix} {file}"


def _format_matrix(matrix: tuple[int, ...]) -> str:
    return " ".join(str(v) for v in matrix)


def to_ldr(model: Model, name: str, author: str = "BrickForgerAI") -> str:
    """Render a Model as LDR text. `name` becomes the file title (line 1)."""
    lines: list[str] = [
        f"0 {name}",
        f"0 Name: {name}.ldr",
        f"0 Author: {author}",
        "0 !LDRAW_ORG Unofficial_Model",
        "0 BFC CERTIFY CCW",
        "0 // Generated by BrickForgerAI (core/brickforge). Do not hand-edit.",
        "",
    ]

    for brick in model:
        x, y, z = placement_to_ldraw(
            brick.pos,
            *brick.part.footprint,
            brick.part.height_plates,
            brick.rotation,
            local_offset=brick.part.local_offset,
            y_anchor=brick.part.y_anchor,
        )
        line = LDR_LINE_TEMPLATE.format(
            color=brick.color,
            x=x,
            y=y,
            z=z,
            matrix=_format_matrix(brick.rotation.matrix),
            file=brick.part.ldraw_file,
        )
        lines.append(line)

    return "\n".join(lines) + "\n"


def save_ldr(model: Model, path: str | Path, name: str | None = None, author: str = "BrickForgerAI") -> Path:
    """Write a Model to `path` as an .ldr file. If `name` is omitted, the
    file's stem is used as the model title."""
    path = Path(path)
    title = name if name is not None else path.stem
    path.write_text(to_ldr(model, title, author=author), encoding="utf-8")
    return path
